version: 2.1

orbs:
  newman: postman/newman@0.0.2

jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run :
          name: Insatll npm
          command: sudo npm install -g newman
      - run :
          name: Insatll html
          command: npm install -g newman-reporter-htmlextra
      - newman/newman-run:
          collection: ./Test.postman_collection.json
          additional-options: -r cli,htmlextra
      - run :
          name: Insatll Depenedices
          command: apk add --update ca-certificates openssl && update-ca-certificates
      - run :
          name: Save Results
          command: |
            mkdir -p ~/test-results/newman
            cp ./newman/newman-run-report-*.html ~/test-results/newman/
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/newman
     
            
          

workflows:
  version: 2
  Some Random Workflow:
    jobs:
      - newman-collection-run
