version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
   newman-collection-run:
     executor: newman/postman-newman-docker
     steps:
      - checkout
      - run:
          name: Update NPM
          command: "npm install -g newman"
       - run:
          name: Install Html extra
          command: "npm install -g newman-reporter-htmlextra"
        - newman/newman-run:
          collection: ./Test.postman_collection.json
          folder: ./ PostmanIntergrationWithCircle/newman/test.html
          additional-options: -r cli,junit,htmlextra
     
      - store_artifacts:
          path: PostmanIntergrationWithCircle/newman
workflows:
  version: 2
  Some Random Workflow:
    jobs:
      - newman-collection-run
