# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

orbs:
  # Declare a dependency on the Newman-orb
  newman: postman/newman@0.0.2
# Orchestrate or schedeule a set of jobs

Jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./Test.postman_collection.json
          additional-options: -r cli,junit

workflows:
  version: 2
  workflow:
    jobs:  
      -  newman-collection-run  
